version: "3.7"

services:
  frontend:
    image: projectapp-frontend
    build:
      context: ./frontend
    environment: 
      API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on: 
      - backend

  backend:
    image: projectapp-backend
    build:
      context: ./backend
    ports:
      - "8080:80"
