apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cluster-reader
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cluster-reader-ns
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "limitranges", "persistentvolumeclaims", "pods", "podtemplates", "replicationcontrollers", "resourcequotas", "secrets", "services", "events"]
    verbs: ["get", "list"]

  - apiGroups: ["apps"]
    resources: ["controllerrevisions", "daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list"]

  - apiGroups: ["authorization.k8s.io"]
    resources: ["localsubjectaccessreviews"]
    verbs: ["get", "list"]  

  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list"]

  - apiGroups: ["crd.projectcalico.org", "networking.k8s.io", "extensions"]
    resources: ["networkpolicies", "networksets", "ingresses"]
    verbs: ["get", "list"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list"]
  
  
  