apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cluster-writer
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["*"]
    
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cluster-writer-ns
rules:
  - apiGroups: [""]
    resources: ["bindings", "configmaps", "endpoints", "limitranges", "persistentvolumeclaims", "pods", "podtemplates", "replicationcontrollers", "resourcequotas", "secrets", "services"]
    verbs: ["*"]
    
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["controllerrevisions", "daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["*"]

  - apiGroups: ["authorization.k8s.io"]
    resources: ["localsubjectaccessreviews"]
    verbs: ["create"]  

  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["*"]

  - apiGroups: ["crd.projectcalico.org", "networking.k8s.io", "extensions"]
    resources: ["networkpolicies", "networksets", "ingresses"]
    verbs: ["*"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["*"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["*"]
  
  
  
  