apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops
  namespace: cicd
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
rules:
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: devops
    namespace: cicd
roleRef:
  kind: ClusterRole
  name: cicd-role
  apiGroup: ""
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
  namespace: production
subjects:
  - kind: ServiceAccount
    name: devops
    namespace: cicd
roleRef:
  kind: ClusterRole
  name: cicd-role
  apiGroup: ""