apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodSecurityAutomountServiceAccountToken
metadata:
  name: psp-automount-serviceaccount-token-pod
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: []